#!/usr/bin/env bash
cd $FILE_SERVER_NAME
SCREEN_NAME=`pwgen -0`

cat <<EOF >setting.txt
test=''unnti'_MEM_MIN=20G'
${FILE_SERVER_NAME}_SERVER_PATH="./unnti"
${FILE_SERVER_NAME}_JVM_ARGUMENT="-Xmx$DEFAULT_MEM -Xms$DEFAULT_MEM"
${FILE_SERVER_NAME}_MEM_MAX=20G
${FILE_SERVER_NAME}_MEM_MIN=20G
${FILE_SERVER_NAME}_JAVA_HOME=java
${FILE_SERVER_NAME}_SCREEN_NAME="${SCREEN_NAME}"
${FILE_SERVER_NAME}_pid="none"
#ステータス
STATUS="offline"
EOF
